/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

/**
 *
 * @author Lais Acosta
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        CadastroCidade = new javax.swing.JMenuItem();
        ListarCidade = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CadastroPessoa = new javax.swing.JMenuItem();
        ListarPessoas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cidade");

        CadastroCidade.setText("Cadastro");
        CadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroCidadeActionPerformed(evt);
            }
        });
        jMenu1.add(CadastroCidade);

        ListarCidade.setText("Lista");
        ListarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCidadeActionPerformed(evt);
            }
        });
        jMenu1.add(ListarCidade);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pessoa");

        CadastroPessoa.setText("Cadastro");
        CadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(CadastroPessoa);

        ListarPessoas.setText("Lista");
        ListarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPessoasActionPerformed(evt);
            }
        });
        jMenu2.add(ListarPessoas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPessoasActionPerformed
        PessoaListar p = new PessoaListar();
        p.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        p.setVisible(true);
    }//GEN-LAST:event_ListarPessoasActionPerformed

    private void CadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroPessoaActionPerformed
        PessoaJFrame p = new PessoaJFrame();
        p.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        p.setVisible(true);
    }//GEN-LAST:event_CadastroPessoaActionPerformed

    private void CadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroCidadeActionPerformed
        CidadeJFrame c = new CidadeJFrame();
        c.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        c.setVisible(true);
    }//GEN-LAST:event_CadastroCidadeActionPerformed

    private void ListarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCidadeActionPerformed
        CidadeListar c = new CidadeListar();
        c.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        c.setVisible(true);
    }//GEN-LAST:event_ListarCidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroCidade;
    private javax.swing.JMenuItem CadastroPessoa;
    private javax.swing.JMenuItem ListarCidade;
    private javax.swing.JMenuItem ListarPessoas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
